name: "FRP Client"
version: "1.0.6"
slug: "frp_client"
description: "可以通过端口转发实现远程访问本地 Home Assistant OS"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
host_network: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
map:
  - share:rw
options:
  serverAddr: fnos.f.17paixie.com
  serverPort: 7000
  authToken: "5989598"
  localIP: "192.168.123.9"
  localPort: 8123
  proxyName: homeassistant
  customDomain: ha99.f.17paixie.com
schema:
  serverAddr: str
  serverPort: int
  authToken: str
  localIP: str
  localPort: int
  proxyName: str
  customDomain: str
