serverAddr = "your_server_addr"
serverPort = 7000
authToken = "123456789"

[[proxies]]
type = "http"
localIP = "your_local_ip"
localPort = 8123
name = "your_proxy_name"
customDomains = "your_domain"
tls = true
